version: '3.8'

services:
  # Serviço do Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped

  # Serviço do Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: 'http://localhost:3001'
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped