name: CI de Testes e Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate: # Renomeei o job para "validate" para ser mais descritivo
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código-fonte
        uses: actions/checkout@v4

      - name: Usar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' 

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar Testes
        run: npm test
      
      - name: Verificar Build de Produção
        run: npm run build --workspaces --if-present